name: Get the menu and create poll
on:
  # schedule:
  #   - cron: '0 10 * * 5' # 10:00 on Friday in UTC, which is 12:00 in CEST
  push 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run script
      run: python3 poll.py
      env:
        STRAW_POLL_TOKEN: ${{ secrets.STRAW_POLL_TOKEN }}
        SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
    - name: Upload URL
      uses: actions/upload-artifact@v4
      with:
        name: url.txt
        path: url.txt
    - name: Commit and push
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add url.txt menu.txt
        git commit -m "Add URL artifact"
        git push
      