name: Get the menu and create poll
on:
  # schedule:
  #   - cron: '0 12 * * 5'
  push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run script
      run: python3 crawler.py
      env:
        STRAW_POLL_TOKEN: ${{ secrets.STRAW_POLL_TOKEN }}
        SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
    - name: Upload URL
      uses: actions/upload-artifact@v4
      with:
        name: url
        path: url.txt
    - name: Save menu
      uses: actions/upload-artifact@v4
      with:
        name: menu
        path: menu.txt