name: Weekly Reminder
on:
  schedule:
    - cron: "30 9 * * 1"  # Every Monday at 10:30 am CEST
  # push
jobs:
  reminder:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8 
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Run reminder script
      run: python3 reminder.py
      env:
        SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
        STRAW_POLL_TOKEN: ${{ secrets.STRAW_POLL_TOKEN }}
