name: Give the results
on:
  schedule:
    - cron: '30 14 * * 5' #'30 10 * * 1' # 10:30 on Monday in UTC, which is 12:30 in CEST
  # push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run script
      run: python3 results.py
      env:
        STRAW_POLL_TOKEN: ${{ secrets.STRAW_POLL_TOKEN }}
        SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
    - name: Upload results
      uses: actions/upload-artifact@v4
      with:
        name: results.txt
        path: results.txt
    - name: Commit and push
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add results.txt
        git commit -m "Add results"
        git push
